#!/bin/sh -e

. /usr/share/debconf/confmodule

case "$1" in
    purge)
	if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
	    . /usr/share/dbconfig-common/dpkg/postrm.mysql
	    db_get mythtv/mysql_mythtv_dbname
	    database="$RET"
	    dbc_go $database $@
	fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
